// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/api.proto

package apiconnect

import (
	context "context"
	errors "errors"
	api "github.com/augustoroman/taskmaster/api"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "api.TaskService"
)

// TaskServiceClient is a client for the api.TaskService service.
type TaskServiceClient interface {
	Create(context.Context, *connect_go.Request[api.CreateRequest]) (*connect_go.Response[api.CreateResponse], error)
	List(context.Context, *connect_go.Request[api.ListRequest]) (*connect_go.Response[api.ListResponse], error)
	Get(context.Context, *connect_go.Request[api.GetRequest]) (*connect_go.Response[api.GetResponse], error)
	Update(context.Context, *connect_go.Request[api.UpdateRequest]) (*connect_go.Response[api.UpdateResponse], error)
	Do(context.Context, *connect_go.Request[api.DoRequest]) (*connect_go.Response[api.DoResponse], error)
	Delete(context.Context, *connect_go.Request[api.DeleteRequest]) (*connect_go.Response[api.DeleteResponse], error)
}

// NewTaskServiceClient constructs a client for the api.TaskService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &taskServiceClient{
		create: connect_go.NewClient[api.CreateRequest, api.CreateResponse](
			httpClient,
			baseURL+"/api.TaskService/Create",
			opts...,
		),
		list: connect_go.NewClient[api.ListRequest, api.ListResponse](
			httpClient,
			baseURL+"/api.TaskService/List",
			opts...,
		),
		get: connect_go.NewClient[api.GetRequest, api.GetResponse](
			httpClient,
			baseURL+"/api.TaskService/Get",
			opts...,
		),
		update: connect_go.NewClient[api.UpdateRequest, api.UpdateResponse](
			httpClient,
			baseURL+"/api.TaskService/Update",
			opts...,
		),
		do: connect_go.NewClient[api.DoRequest, api.DoResponse](
			httpClient,
			baseURL+"/api.TaskService/Do",
			opts...,
		),
		delete: connect_go.NewClient[api.DeleteRequest, api.DeleteResponse](
			httpClient,
			baseURL+"/api.TaskService/Delete",
			opts...,
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	create *connect_go.Client[api.CreateRequest, api.CreateResponse]
	list   *connect_go.Client[api.ListRequest, api.ListResponse]
	get    *connect_go.Client[api.GetRequest, api.GetResponse]
	update *connect_go.Client[api.UpdateRequest, api.UpdateResponse]
	do     *connect_go.Client[api.DoRequest, api.DoResponse]
	delete *connect_go.Client[api.DeleteRequest, api.DeleteResponse]
}

// Create calls api.TaskService.Create.
func (c *taskServiceClient) Create(ctx context.Context, req *connect_go.Request[api.CreateRequest]) (*connect_go.Response[api.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// List calls api.TaskService.List.
func (c *taskServiceClient) List(ctx context.Context, req *connect_go.Request[api.ListRequest]) (*connect_go.Response[api.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Get calls api.TaskService.Get.
func (c *taskServiceClient) Get(ctx context.Context, req *connect_go.Request[api.GetRequest]) (*connect_go.Response[api.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Update calls api.TaskService.Update.
func (c *taskServiceClient) Update(ctx context.Context, req *connect_go.Request[api.UpdateRequest]) (*connect_go.Response[api.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Do calls api.TaskService.Do.
func (c *taskServiceClient) Do(ctx context.Context, req *connect_go.Request[api.DoRequest]) (*connect_go.Response[api.DoResponse], error) {
	return c.do.CallUnary(ctx, req)
}

// Delete calls api.TaskService.Delete.
func (c *taskServiceClient) Delete(ctx context.Context, req *connect_go.Request[api.DeleteRequest]) (*connect_go.Response[api.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the api.TaskService service.
type TaskServiceHandler interface {
	Create(context.Context, *connect_go.Request[api.CreateRequest]) (*connect_go.Response[api.CreateResponse], error)
	List(context.Context, *connect_go.Request[api.ListRequest]) (*connect_go.Response[api.ListResponse], error)
	Get(context.Context, *connect_go.Request[api.GetRequest]) (*connect_go.Response[api.GetResponse], error)
	Update(context.Context, *connect_go.Request[api.UpdateRequest]) (*connect_go.Response[api.UpdateResponse], error)
	Do(context.Context, *connect_go.Request[api.DoRequest]) (*connect_go.Response[api.DoResponse], error)
	Delete(context.Context, *connect_go.Request[api.DeleteRequest]) (*connect_go.Response[api.DeleteResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/api.TaskService/Create", connect_go.NewUnaryHandler(
		"/api.TaskService/Create",
		svc.Create,
		opts...,
	))
	mux.Handle("/api.TaskService/List", connect_go.NewUnaryHandler(
		"/api.TaskService/List",
		svc.List,
		opts...,
	))
	mux.Handle("/api.TaskService/Get", connect_go.NewUnaryHandler(
		"/api.TaskService/Get",
		svc.Get,
		opts...,
	))
	mux.Handle("/api.TaskService/Update", connect_go.NewUnaryHandler(
		"/api.TaskService/Update",
		svc.Update,
		opts...,
	))
	mux.Handle("/api.TaskService/Do", connect_go.NewUnaryHandler(
		"/api.TaskService/Do",
		svc.Do,
		opts...,
	))
	mux.Handle("/api.TaskService/Delete", connect_go.NewUnaryHandler(
		"/api.TaskService/Delete",
		svc.Delete,
		opts...,
	))
	return "/api.TaskService/", mux
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) Create(context.Context, *connect_go.Request[api.CreateRequest]) (*connect_go.Response[api.CreateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.TaskService.Create is not implemented"))
}

func (UnimplementedTaskServiceHandler) List(context.Context, *connect_go.Request[api.ListRequest]) (*connect_go.Response[api.ListResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.TaskService.List is not implemented"))
}

func (UnimplementedTaskServiceHandler) Get(context.Context, *connect_go.Request[api.GetRequest]) (*connect_go.Response[api.GetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.TaskService.Get is not implemented"))
}

func (UnimplementedTaskServiceHandler) Update(context.Context, *connect_go.Request[api.UpdateRequest]) (*connect_go.Response[api.UpdateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.TaskService.Update is not implemented"))
}

func (UnimplementedTaskServiceHandler) Do(context.Context, *connect_go.Request[api.DoRequest]) (*connect_go.Response[api.DoResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.TaskService.Do is not implemented"))
}

func (UnimplementedTaskServiceHandler) Delete(context.Context, *connect_go.Request[api.DeleteRequest]) (*connect_go.Response[api.DeleteResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.TaskService.Delete is not implemented"))
}
